blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/MITHU-06/Canteen-Preorder-System/discussions
    about: Ask questions, share ideas, and connect with other developers and contributors.
